apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-configmap
data:
  pdns.conf: |
    launch=gmysql:dns
    gmysql-dns-host=mariadb-service
    gmysql-dns-dbname=powerdns
    gmysql-dns-user=powerdns
    gmysql-dns-password=powerdns
    gmysql-dns-dnssec=yes
