apiVersion: v1
kind: Service
metadata:
  name: powerdns-service
spec:
  selector:
    app: powerdns
  ports:
  - port: 53
    targetPort: 53
  - port: 53
    targetPort: 53
    protocol: UDP
  type: LoadBalancer
