apiVersion: v1
kind: Service
metadata:
  name: powerdns-service
spec:
  selector:
    app: powerdns
  ports:
  - name: tcp
    port: 53
    targetPort: 53
  - name: udp
    port: 53
    targetPort: 53
    protocol: UDP
  type: LoadBalancer
